### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [biopython/biopython-wheels#10]
Problem
---------
On aarch64, ‘pip install biopython’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install biopython’ should download the wheels from pypi

@peterjc  Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by peterjc** [comment]
I'm curious - other than the recent Apple ARM64 machines (under Linux or macOS), where do you expect this to be useful? Or is that your usecase?

**Comment by odidev** [comment]
It can be useful as -

- The Arm architecture has been available on AWS (Graviton2) for about 2 years now and has seen a lot of adoption by various organizations. The install base of Arm users is growing at a rapid pace.

- Oracle cloud will be releasing Arm based Compute Shapes in the future. Please see [here](https://www.anandtech.com/show/16100/oracle-announces-upcoming-cloud-compute-instances-ice-lake-and-milan-a100-and-altra#:~:text=OCI%E2%80%99s%20Arm%20instances%20will%20clock%20as%20high%20as,%E2%80%93%20OCI%20is%20refreshing%20its%20GPU%20compute%20instances)

- Generally, there is a lot of momentum behind various products switching to Arm based CPUs. For example, the Microsoft surface Pro X is an Arm based device.

**Comment by peterjc** [comment]
OK, I've merged your PR - thank you. That should build and cache the ARM wheels here:

https://anaconda.org/multibuild-wheels-staging/biopython/files?version=1.78

I'll need to manually transfer the new wheels to PyPI later - are you in a position to sanity test them first?

**Comment by peterjc** [comment]
That's new Linux aarch64 wheels for Python 3.6, 3.7, 3.8 and 3.9 on the staging area now. Ideally I'd like at least one of them sanity tested before copying them to PyPI.

**Comment by odidev** [comment]
I ran the tests on wheel for python3.8 and they are running fine.

**Comment by peterjc** [comment]
Done,

```
$ twine upload biopython-1.78-*_aarch64.whl
Uploading distributions to https://upload.pypi.org/legacy/
Uploading biopython-1.78-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
100%|██████████████████████████████████████████████████████████████████████| 2.16M/2.16M [00:05<00:00, 385kB/s]
Uploading biopython-1.78-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
100%|██████████████████████████████████████████████████████████████████████| 2.16M/2.16M [00:04<00:00, 468kB/s]
Uploading biopython-1.78-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
100%|██████████████████████████████████████████████████████████████████████| 2.16M/2.16M [00:04<00:00, 525kB/s]
Uploading biopython-1.78-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
100%|██████████████████████████████████████████████████████████████████████| 2.16M/2.16M [00:04<00:00, 459kB/s]

View at:
https://pypi.org/project/biopython/1.78/
```

And for the record,

```
$ sha256sum biopython-1.78-*_aarch64.whl
cfb93842501ebc0e0ef6520daddcbeeefc9b61736972580917dafd5c8a5a8041  biopython-1.78-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
1df0bce7fd5e2414d6e18c9229fa0056914d2b9041531c71cac48f38a622142d  biopython-1.78-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
d15d09bfe0d3a8a416a596a3909d9718c811df852d969592b4fa9e0da9cf7375  biopython-1.78-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
639461a1ac5765406ec8ab8ed619845351f2ff22fed734d86e09e4a7b7719a08  biopython-1.78-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
```

Closing issue - thank you!
